# Generated by Django 4.2 on 2023-04-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='User',
            new_name='user',
        ),
    ]
