# Generated by Django 4.2 on 2023-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_content_application_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='content',
            field=models.TextField(default=" '"),
        ),
    ]
