# Generated by Django 4.2 on 2023-04-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
