# Generated by Django 4.2 on 2023-04-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_conversationmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessages',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='conversationmessages',
            old_name='cr_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversationmessages',
            old_name='cr_by',
            new_name='created_by',
        ),
    ]
